on:
  workflow_call:
    inputs:
      RELEASE_VERSION:
        description: "The version to build the package"
        required: true
        type: string

jobs:
  Build:
    name: 'Build Package'
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
         
      - name: Build Package
        id: build
        run: |
          # BUILDTYPE is used by the build of premium firmware modules such
          # as print-process-reporting. "PRODUCTION" triggers the build of
          # an encrypted firmware module using Ultimaker/umlicensemanager.
          # Other firmware components ignore this.
          export BUILDTYPE=PRODUCTION
          # Encryption key for UMMOD file in "PRODUCTION" build mode.
          # See umlicensemanager documentation
          export UMLM_ENCRYPTION_KEY="${{ secrets.UMLM_ENCRYPTION_KEY }}"

          export RELEASE_VERSION="${{ env.RELEASE_VERSION }}"
          echo "RELEASE_VERSION: ${RELEASE_VERSION}"
          
          ./build_for_ultimaker.sh -a build
          
      - name: Upload Artifact (Built package)
        uses: actions/upload-artifact@v4
        with:
          name: build-package
          path: "./*.deb"

      - name: Dump GitHub context
        if: ${{ always() }}
        env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
           JOB_CONTEXT: ${{ toJson(job) }}
           STEPS_CONTEXT: ${{ toJson(steps) }}
           RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "${GITHUB_CONTEXT}"
          echo "${JOB_CONTEXT}"
          echo "${STEPS_CONTEXT}"
          echo "${RUNNER_CONTEXT}"
