name: Release a new docker image upon tagging

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE_NAME:
        description: "The name of the docker image. E.g.: um-kernel"
        required: true
        type: string

      DOCKER_TAG_PREFIX:
        description: "The prefix used to tag the image. It will be used to extract the version. E.g.: docker_img-"
        required: false
        default: 'docker_img-'
        type: string

env:
  DOCKER_IMAGE_NAME: ghcr.io/lulzbot3d/${{ inputs.DOCKER_IMAGE_NAME }}
  DOCKER_TAG_PREFIX: ${{ inputs.DOCKER_TAG_PREFIX }}
  
jobs:
  Build:
    name: 'Build and Release Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login in GitHub Container Registry
        id: ghcr_login
        run: |
          echo "" | docker login ghcr.io -u $ --password-stdin
                   
      - name: Build Docker Image
        id: build
        run: |
          # Remove the tag prefix to make the version
          export DOCKER_IMAGE_VERSION="${GITHUB_REF_NAME##${DOCKER_TAG_PREFIX}}"
          export DOCKER_IMAGE_NAME
          echo "DOCKER_IMAGE_NAME: ${DOCKER_IMAGE_NAME}"
          echo "DOCKER_IMAGE_VERSION: ${DOCKER_IMAGE_VERSION}"
          
          # Just generate a new docker image, so pass action = none          
          ./build_for_ultimaker.sh -a docker_build
          docker images

      - name: Release Docker Image to Github Packages
        id: release
        run: |
          export DOCKER_IMAGE_VERSION="${GITHUB_REF_NAME##${DOCKER_TAG_PREFIX}}"
          export DOCKER_IMAGE_NAME
          echo "DOCKER_IMAGE_NAME: ${DOCKER_IMAGE_NAME}"
          echo "DOCKER_IMAGE_VERSION: ${DOCKER_IMAGE_VERSION}"
          docker push "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}"

      - name: Dump GitHub context
        if: ${{ always() }}
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"

